### ISSUE TITLE
Doesn't work from client

### ISSUE THREAD

**Issue by sodik82** [viruschidai/validate-vat-ts#4]
I am getting

```
Access to fetch at 'http://ec.europa.eu/taxation_customs/vies/services/checkVatService' from origin 'http://localhost:6006' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I tried also `no-cors` but it is not useful as you can't read response.

https://stackoverflow.com/questions/54896998/how-to-process-fetch-response-from-an-opaque-type

Not sure what to do with it.

**Comment by viruschidai** [comment]
Was overstated in the readme, seems cannot directly call the VIEW soap service from browser. If you really want to call the service from browser, probably have a proxy route in your API server.

**Comment by benbucksch** [comment]
Yes, this is a server-side component. You cannot contact the EU server directly from the browser.

**Comment by zedrdave** [comment]
OK thanks, I guess I'll write my own code or use another package.

**Comment by benbucksch** [comment]
It's not a question of code. Browsers do not allow your website to contact arbitrary servers on the Internet.

**Comment by thebillg** [comment]
I think the EU gov server does not like directly access from browser due to CORS settings. Unless there is a service in the middle available that allows directly access from browser with CORS setting like `Access-Control-Allow-Origin: *`, you have to call it from server side.
